# Site settings
title: "Dhaval J. Savalia"
description: " Pythonista // Open Source // Cloud // Automation"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dhaval J. Savalia"
resume_title:                   "Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dhaval.savalia6@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "7405505665"
resume_contact_address:         "Surat Area, Gujarat, IN"

resume_header_contact_info:     "Surat Area, Gujarat, IN • 7405505665 • dhaval.savalia6@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Something goes here but I haven't decided yet!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dhavalsavalia"
  resume_twitter_url:           "http://twitter.com/DhavalSavalia"
  #resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dhavalsavalia"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://dhavalsavalia.github.io"
  resume_medium_url:            "https://medium.com/@dhavalsavalia"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
